[JBIDE-19776] Create and use Mars RC2 target-platform
Adding the Jetty 9 bundles in versoin 9.2.10 that are missing for LiveReload
(LiveReload would use a mix of 9.2.9 and 9.2.10 bundles, which causes errors because of
some  java.lang.NoClassDefFoundError: org/eclipse/jetty/util/thread/SpinLock)